/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEmpleados;
import Modelo.Empleado;
import Modelo.EmpleadosTableModel;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class formNuevoEmpleado extends javax.swing.JFrame {

    ArrayList<Empleado> lista;

    /*nuevo se utiliza como una bandera en el caso que sea 1 se carga uno nuevo
     en el caso de que sea 2, se edita un empleado existente, en el caso que seas 
     0 se pedira que se seleccione alguna de las opciones */
    int nuevo;

    public formNuevoEmpleado() {
        initComponents();
        this.setResizable(false);
        lista = new ArrayList<>();
        grupoSexo.add(rbFemenino);
        grupoSexo.add(rbMasculino);
        nuevo = 0;
        foco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        grupoSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtTelefonoEmer = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        rbMasculino = new javax.swing.JRadioButton();
        rbFemenino = new javax.swing.JRadioButton();
        cboActivo = new javax.swing.JCheckBox();
        cboSuplencia = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        cbTipoEmpleado = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPasw1 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPasw2 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar Empleados");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevoChico.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Agregar un nuevo empleado");
        btnNuevo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar empleado");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/EliminarUsuario.png"))); // NOI18N
        btnEliminar.setText("Desactivar");
        btnEliminar.setToolTipText("Eliminar un empleado");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/CancelarCambios.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setToolTipText("Volver al menu principal");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar Cambios");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel10.setText("Codigo :");

        jLabel11.setText("Nombre* :");

        jLabel12.setText("Apellido* :");

        jLabel13.setText("Fecha de Nacimiento* :");

        jLabel14.setText("DNI :");

        jLabel15.setText("Sexo* :");

        jLabel16.setText("Direccion :");

        jLabel17.setText("Telefono :");

        jLabel18.setText("Telefono Emergencia :");

        txtNombre.setEnabled(false);

        txtApellido.setEnabled(false);

        txtDni.setEnabled(false);

        txtDireccion.setEnabled(false);

        txtTelefono.setEnabled(false);

        txtTelefonoEmer.setEnabled(false);

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCodigo.setText("-");

        jdcFecha.setDateFormatString("dd-MM-yyyy");
        jdcFecha.setEnabled(false);

        rbMasculino.setText("Masculino");
        rbMasculino.setEnabled(false);

        rbFemenino.setText("Femenino");
        rbFemenino.setEnabled(false);

        cboActivo.setSelected(true);
        cboActivo.setText("Activo ");
        cboActivo.setToolTipText("Indica si el profesor trabaja actualmente");
        cboActivo.setEnabled(false);

        cboSuplencia.setText("Suplencias");
        cboSuplencia.setToolTipText("Inidica si el profesor acepta suplencias ");
        cboSuplencia.setEnabled(false);

        jLabel3.setText("Comentario :");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        txtComentario.setEnabled(false);
        jScrollPane2.setViewportView(txtComentario);

        cbTipoEmpleado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atencion al cliente", "Profesor", "Administrador" }));
        cbTipoEmpleado.setEnabled(false);
        cbTipoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoEmpleadoActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo de empleado :");

        jLabel6.setText("Usuario* :");

        txtUsuario.setEnabled(false);

        txtPasw1.setEnabled(false);
        txtPasw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasw1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Constraseña* :");

        jLabel8.setText("Repetir Constraseña* :");
        jLabel8.setToolTipText("");

        txtPasw2.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefonoEmer, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbMasculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbFemenino))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(cboActivo)
                                    .addGap(18, 18, 18)
                                    .addComponent(cboSuplencia))))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUsuario)
                            .addComponent(txtPasw1)
                            .addComponent(txtPasw2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jdcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(rbMasculino)
                            .addComponent(rbFemenino))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(txtTelefonoEmer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboActivo)
                            .addComponent(cboSuplencia)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasw1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPasw2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "DNI"
            }
        ));
        tblEmpleados.setFocusable(false);
        tblEmpleados.getTableHeader().setReorderingAllowed(false);
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblEmpleadosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        habilitar(true);
        cboActivo.setSelected(true);
        borrar();
        tblEmpleados.clearSelection();
        nuevo = 1;

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habilitar(false);
        tblEmpleados.clearSelection();
        borrar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbTipoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoEmpleadoActionPerformed

    }//GEN-LAST:event_cbTipoEmpleadoActionPerformed

    private void txtPasw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasw1ActionPerformed

    }//GEN-LAST:event_txtPasw1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int codigoAlumno = tblEmpleados.getSelectedRow();
        if (codigoAlumno >= 0) {
            ControladorEmpleados ce = new ControladorEmpleados();
            ce.desactivarEmpleado(Integer.parseInt(lblCodigo.getText()));
            JOptionPane.showMessageDialog(this, "Se desactivo la cuenta del empleado correctamente!", "Desactivar cuenta", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar la cuenta del empleado que desea desactivar", "Desactivar cuenta", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Obtengo todos los empleados de la base de datos
        ControladorEmpleados ce = new ControladorEmpleados();
        lista = ce.buscarEmpleados();
        //Los cargo en la tabla
        EmpleadosTableModel modelEmpleado = new EmpleadosTableModel(lista);
        tblEmpleados.setModel(modelEmpleado);
    }//GEN-LAST:event_formWindowActivated

    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
       
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Empleado e = new Empleado();

        //Valido que almenos los campos necesarios esten cargados
        if (validarCampos()) {
            //Recupero todos los datos cargados y los seteo en el objeto
            e.setNombre(txtNombre.getText());
            e.setApellido(txtApellido.getText());
            e.setComentario(txtComentario.getText());
            e.setActivo(cboActivo.isSelected());
            if (rbFemenino.isSelected()) {
                e.setSexo(false);
            } else {
                e.setSexo(true);
            }
            e.setDireccion(txtDireccion.getText());
            e.setSuplencia(cboSuplencia.isSelected());
            e.setTelefono(txtTelefono.getText());
            e.setTelefonoAyuda(txtTelefonoEmer.getText());
            e.setDni(txtDni.getText());
            e.setUsuario(txtUsuario.getText());

            e.setContraseña(txtPasw1.getText());
            e.setTipoEmpleado(cbTipoEmpleado.getSelectedIndex() + 1);

            //Necesito convertir formato date a timestamp para poder almacenarlo
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss.SSS");
            String day = df.format(jdcFecha.getDate());
            e.setFechaNac(Timestamp.valueOf(day));

            ControladorEmpleados ce = new ControladorEmpleados();

            if (nuevo == 1) {
                ce.cargarNuevoEmpleado(e);
                JOptionPane.showMessageDialog(this, "Cargo el empleado correctamente!","Nuevo Empleado",JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (nuevo == 2) {
                    e.setCodEmpleado(Integer.parseInt(lblCodigo.getText()));
                    ce.actualizarEmpleado(e);
                    JOptionPane.showMessageDialog(this, "Se actualizo el empleado correctamente!","Editar Empleado",JOptionPane.INFORMATION_MESSAGE);
                }
            }
            habilitar(false);
            borrar();
            nuevo = 0;
            tblEmpleados.clearSelection();
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private boolean validarCampos() {
        Boolean validar = true;

        try {
            if (txtNombre.getText().isEmpty()) {
                throw new Exception("LLene el campo nombre.");
            }

            if (txtApellido.getText().isEmpty()) {
                throw new Exception("LLene el campo apellido.");
            }

            if (jdcFecha.getDate() == null) {
                throw new Exception("Ingrese la fecha de nacimiento");
            }

            if(txtDni.getText().isEmpty()){
                throw new Exception("Ingrese el DNI del empleado");                
            }
            
            if(!isNumeric(txtDni.getText())){
                throw new Exception("El DNI debe ser de tipo numerico");
            }
            
            if (rbFemenino.isSelected() == false && rbMasculino.isSelected() == false) {
                throw new Exception("Seleccione un genero");
            }

            if (txtUsuario.getText().isEmpty()) {
                throw new Exception("Ingrese un usuario");
            }

            if (!txtPasw1.getText().equals(txtPasw2.getText())) {
                throw new Exception("Las contraseñas no coinciden.");
            }

            if (!txtTelefono.getText().isEmpty()) {
                if (!isNumeric(txtTelefono.getText())) {
                    throw new Exception("El telefono debe ser un campo numerico");
                }
            }

            if (!txtTelefonoEmer.getText().isEmpty()) {
                if (!isNumeric(txtTelefonoEmer.getText())) {
                    throw new Exception("El telefono de emergencia debe ser un campo numerico");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(),"Error",JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return validar;
    }


    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblEmpleados.getSelectedRow() >= 0) {
            habilitar(true);
            nuevo = 2;
        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un empleado para poder editarlo","Editar Empleado",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tblEmpleadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMousePressed
        try {
            if(!tblEmpleados.isEnabled()){
                throw new Exception("");
            }
            int seleccionado = tblEmpleados.getSelectedRow();
            Integer dato = (Integer) tblEmpleados.getValueAt(seleccionado, 0);
            cargarCampos(dato);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La tabla no esta habilitada, ya que se estan editando campos","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblEmpleadosMousePressed

    public void cargarCampos(int i) {
        borrar();
        ControladorEmpleados ce = new ControladorEmpleados();

        Empleado empleado = ce.buscarEmpleado(i);

        if (empleado != null) {
            lblCodigo.setText(Integer.toString(empleado.getCodEmpleado()));
            txtNombre.setText(empleado.getNombre());
            txtApellido.setText(empleado.getApellido());
            jdcFecha.setDate(empleado.getFechaNac());
            if (empleado.getSexo()) {
                rbMasculino.setSelected(true);
            } else {
                rbFemenino.setSelected(true);
            }

            txtDireccion.setText(empleado.getDireccion());
            txtDni.setText(empleado.getDni());
            txtTelefono.setText(empleado.getTelefono());
            txtTelefonoEmer.setText(empleado.getTelefonoAyuda());
            txtComentario.setText(empleado.getComentario());
            cboActivo.setSelected(empleado.getActivo());
            cboSuplencia.setSelected(empleado.getSuplencia());
            txtUsuario.setText(empleado.getUsuario());
            txtPasw1.setText(empleado.getContraseña());
            txtPasw2.setText(empleado.getContraseña());
            cbTipoEmpleado.setSelectedIndex(empleado.getTipoEmpleado() - 1);

        }
    }

    private void habilitar(Boolean x) {
        txtNombre.setEnabled(x);
        txtApellido.setEnabled(x);
        jdcFecha.setEnabled(x);
        rbFemenino.setEnabled(x);
        rbMasculino.setEnabled(x);
        txtDireccion.setEnabled(x);
        txtDni.setEnabled(x);
        txtTelefono.setEnabled(x);
        txtTelefonoEmer.setEnabled(x);
        btnNuevo.setEnabled(!x);
        btnEditar.setEnabled(!x);
        btnEliminar.setEnabled(!x);
        btnCancelar.setEnabled(x);
        txtComentario.setEnabled(x);
        cboActivo.setEnabled(x);
        cboSuplencia.setEnabled(x);
        cbTipoEmpleado.setEnabled(x);
        txtUsuario.setEnabled(x);
        txtPasw1.setEnabled(x);
        txtPasw2.setEnabled(x);
        btnGuardar.setEnabled(x);
        tblEmpleados.setEnabled(!x);
    }

    private void borrar() {
        txtNombre.setText("");
        txtApellido.setText("");
        rbFemenino.setSelected(false);
        rbMasculino.setSelected(false);
        txtDireccion.setText("");
        txtDni.setText("");
        txtTelefono.setText("");
        txtTelefonoEmer.setText("");
        txtComentario.setText("");
        cboActivo.setSelected(true);
        cboSuplencia.setSelected(false);
        jdcFecha.setDate(null);
        cbTipoEmpleado.setSelectedIndex(0);
        txtUsuario.setText("");
        txtPasw1.setText("");
        txtPasw2.setText("");
        lblCodigo.setText("-");
        nuevo = 0;
        cboActivo.setSelected(false);

    }

    public void foco() {
        btnNuevo.setNextFocusableComponent(btnEditar);
        btnEditar.setNextFocusableComponent(btnEliminar);
        btnEliminar.setNextFocusableComponent(btnGuardar);
        btnGuardar.setNextFocusableComponent(btnEliminar);
        btnEliminar.setNextFocusableComponent(btnSalir);
        txtNombre.setNextFocusableComponent(txtApellido);
        txtApellido.setNextFocusableComponent(jdcFecha);
        jdcFecha.setNextFocusableComponent(txtDni);
        txtDni.setNextFocusableComponent(rbMasculino);
        rbMasculino.setNextFocusableComponent(rbFemenino);
        rbFemenino.setNextFocusableComponent(txtDireccion);
        txtDireccion.setNextFocusableComponent(txtTelefono);
        txtTelefono.setNextFocusableComponent(txtTelefonoEmer);
        txtTelefonoEmer.setNextFocusableComponent(cboActivo);
        cboActivo.setNextFocusableComponent(cboSuplencia);
        cboSuplencia.setNextFocusableComponent(cbTipoEmpleado);
        cbTipoEmpleado.setNextFocusableComponent(txtUsuario);
        txtUsuario.setNextFocusableComponent(txtPasw1);
        txtPasw1.setNextFocusableComponent(txtPasw2);
        txtPasw2.setNextFocusableComponent(txtComentario);
        txtComentario.setNextFocusableComponent(btnGuardar);
        btnGuardar.setNextFocusableComponent(btnCancelar);

    }

    private static boolean isNumeric(String cadena) {
        try {
            Float.parseFloat(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formNuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formNuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formNuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formNuevoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formNuevoEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbTipoEmpleado;
    private javax.swing.JCheckBox cboActivo;
    private javax.swing.JCheckBox cboSuplencia;
    private javax.swing.ButtonGroup grupoSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private com.toedter.calendar.JDateChooser jdcFecha;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JRadioButton rbFemenino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPasw1;
    private javax.swing.JPasswordField txtPasw2;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoEmer;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
